/**
 * Comprehensive safelist of folder names that must NEVER be flagged as uninstall leftovers.
 * All entries are lowercase. Lookups must normalize to lowercase before checking.
 */

/** R language runtime installation folder. */
export const R_LANGUAGE_RUNTIME_FOLDER = 'r'

export const SAFE_FOLDER_NAMES = new Set([
  // ── Windows core & system ───────────────────────────────────────────
  'microsoft',
  'microsoft corporation',
  'windows',
  'windowsapps',
  'windows nt',
  'windows defender',
  'windows defender advanced threat protection',
  'windows mail',
  'windows media player',
  'windows multimedia platform',
  'windows photo viewer',
  'windows portable devices',
  'windows security',
  'windows sidebar',
  'windowspowershell',
  'internet explorer',
  'common files',
  'uninstall information',
  'reference assemblies',
  'msbuild',
  'desktop',
  'documents',
  'downloads',
  'pictures',
  'videos',
  'music',
  'contacts',
  'favorites',
  'links',
  'saved games',
  'searches',
  '3d objects',
  'onedrive',
  'appdata',

  // ── System infrastructure ───────────────────────────────────────────
  'packages',
  'connecteddevicesplatform',
  'comms',
  'inetcache',
  'history',
  'temporary internet files',
  'default',
  'public',
  'all users',
  'default user',
  'system volume information',
  '$recycle.bin',
  'msocache',
  'perflogs',
  'recovery',
  'config.msi',
  'installer',

  // ── .NET / Visual Studio / Build tools ──────────────────────────────
  '.net',
  'dotnet',
  '.dotnet',
  'assembly',
  'gac_msil',
  'nativeimages_v4.0.30319_64',
  'microsoft.net',
  'microsoft sdks',
  'microsoft sql server',
  'microsoft sql server compact edition',
  'microsoft visual studio',
  'microsoft visual studio 8',
  'microsoft visual studio 9.0',
  'microsoft visual studio 10.0',
  'microsoft visual studio 11.0',
  'microsoft visual studio 12.0',
  'microsoft visual studio 14.0',
  'microsoft visual studio 15.0',
  'microsoft visual studio 16.0',
  'microsoft visual studio 17.0',
  'microsoft shared',
  'microsoft office',
  'microsoft update',
  'microsoft analysis services',
  'visual studio',
  'vs',
  'vswhere',
  'nuget',
  'vcredist',

  // ── Runtimes & languages ────────────────────────────────────────────
  'python',
  'python3',
  'python27',
  'python36',
  'python37',
  'python38',
  'python39',
  'python310',
  'python311',
  'python312',
  'python313',
  'java',
  'javapath',
  'node.js',
  'nodejs',
  'node_modules',
  'go',
  'rust',
  '.rustup',
  '.cargo',
  'ruby',
  'perl',
  'php',
  R_LANGUAGE_RUNTIME_FOLDER,
  'julia',
  'erlang',
  'elixir',
  'haskell',
  'scala',
  'kotlin',
  'swift',
  'zig',
  'deno',
  'bun',
  '.bun',

  // ── Package managers & build systems ────────────────────────────────
  'npm',
  'npm-cache',
  'yarn',
  'pnpm',
  'pnpm-store',
  'pnpm-home',
  'pip',
  'pipx',
  'conda',
  'miniconda3',
  'anaconda3',
  'composer',
  'gradle',
  '.gradle',
  'maven',
  '.m2',
  'cargo',
  'vcpkg',
  'conan',
  'scoop',
  'chocolatey',
  'winget',
  'homebrew',

  // ── GPU / hardware vendors ──────────────────────────────────────────
  'nvidia',
  'nvidia corporation',
  'amd',
  'ati',
  'intel',
  'intel corporation',
  'realtek',
  'realtek semiconductor',
  'logitech',
  'razer',
  'corsair',
  'steelseries',
  'hyperx',
  'creative',
  'creative technology',
  'displaylink',
  'wacom',
  'wacom technology',
  'synaptics',
  'tobii',

  // ── Security / antivirus ────────────────────────────────────────────
  'malwarebytes',
  'avg',
  'avast software',
  'avira',
  'kaspersky lab',
  'eset',
  'bitdefender',
  'norton',
  'mcafee',
  'trend micro',
  'sophos',
  'webroot',
  'crowdstrike',
  'sentinelone',

  // ── Cloud & sync ────────────────────────────────────────────────────
  'google',
  'google chrome',
  'dropbox',
  'box',
  'icloud',
  'mega',
  'nextcloud',
  'owncloud',
  'resilio sync',

  // ── Major applications (always present) ─────────────────────────────
  'mozilla',
  'mozilla firefox',
  'apple',
  'apple computer',
  'adobe',
  'autodesk',
  'oracle',
  'sap',
  'ibm',
  'vmware',
  'citrix',
  'dell',
  'hp',
  'lenovo',
  'asus',
  'acer',

  // ── Dev tools & editors ─────────────────────────────────────────────
  'git',
  'gitkraken',
  'github',
  'github desktop',
  'gh',
  'code',
  'vscode',
  'sublime text',
  'notepad++',
  'jetbrains',
  'neovim',
  'vim',
  'emacs',
  'atom',
  'cursor',
  'windsurf',

  // ── Docker / virtualization ─────────────────────────────────────────
  'docker',
  'docker desktop',
  'wsl',
  'hyper-v',
  'virtualbox',
  'vagrant',
  'podman',

  // ── Electron / Chromium infrastructure ──────────────────────────────
  'electron',
  'crashpad',
  'gpu cache',
  'gpucache',
  'squirrel',
  'squirrel.windows',
  'update.exe',
  'cef',
  'chromium',

  // ── Common data / temp folders ──────────────────────────────────────
  'temp',
  'tmp',
  'cache',
  'caches',
  'logs',
  'log',
  'crash reports',
  'crashdumps',
  'crashreports',
  'thumbnails',
  'recent',
  'history',
  '.cache',
  '.config',
  '.local',
  '.tmp',
  'fontcache',
  'iconcache',

  // ── Gaming platforms ────────────────────────────────────────────────
  'steam',
  'valve',
  'valve corporation',
  'epic games',
  'epicgameslauncher',
  'gog.com',
  'gog galaxy',
  'blizzard entertainment',
  'battle.net',
  'riot games',
  'ubisoft',
  'ubisoft game launcher',
  'electronic arts',
  'ea desktop',
  'origin',
  'xbox',
  'rockstar games',
  'bethesda.net launcher',

  // ── Communication apps ──────────────────────────────────────────────
  'discord',
  'slack',
  'microsoft teams',
  'teams',
  'zoom',
  'telegram desktop',
  'signal',
  'whatsapp',
  'skype',

  // ── Media ───────────────────────────────────────────────────────────
  'spotify',
  'itunes',
  'vlc',
  'obs-studio',
  'obs studio',
  'audacity',
  'gimp',

  // ── Networking / VPN ────────────────────────────────────────────────
  'cisco',
  'openvpn',
  'wireguard',
  'nordvpn',
  'expressvpn',
  'protonvpn',
  'tailscale',

  // ── System utilities ────────────────────────────────────────────────
  '7-zip',
  'winrar',
  'peazip',
  'everything',
  'autohotkey',
  'powertoys',
  'sysinternals',

  // ── Fonts ───────────────────────────────────────────────────────────
  'fonts',
  'windowsfonts',
  'adobe fonts',

  // ── Accessibility / input ───────────────────────────────────────────
  'accessibility',
  'speech',
  'narrator',

  // ── Windows Store / UWP packages ────────────────────────────────────
  'windowsstore',
  'microsoft store',
  'apprepository',

  // ── Miscellaneous known safe ────────────────────────────────────────
  'identities',
  'networklist',
  'dnscache',
  'tracing',
  'wer',
  'cryptnetcache',
  'iconcache',
  'd3dscache',
  'diagnostics',
  'usrclass.dat',
  'ntuser.dat',
  'softwareclasses',
  'networkprofiles',
  'application data',
  'local settings',
  'templates',
  'start menu',
  'programs',
  'startup',
  'sendto',
  'printhood',
  'nethood',
])

/**
 * Folder name prefixes that should always be considered safe.
 * A folder is safe if its lowercase name starts with any of these strings.
 */
export const SAFE_PREFIXES = [
  'microsoft.',
  'microsoft ',
  'windows.',
  'windows ',
  'msvc',
  'vc_redist',
  'vcredist',
  'dotnet',
  '.net',
  'nvidia',
  'intel(',
  'intel ',
  'python3',
  'python2',
  'node-v',
  'jdk',
  'jdk-',
  'jre',
  'jre-',
  'adoptopenjdk',
  'eclipse adoptium',
  'amazon corretto',
  'zulu',
  'liberica',
  'graalvm',
  'windowsapps',
  'program',
  'system',
]

/**
 * Precise checks for special folder shapes that are always safe.
 * GUID-style folders {xxxxxxxx-...} and Windows KB update folders (KBnnnnnn).
 */
export function isSafeFolder(folderName: string): boolean {
  const lower = folderName.toLowerCase()

  if (SAFE_FOLDER_NAMES.has(lower)) return true

  for (const prefix of SAFE_PREFIXES) {
    if (lower.startsWith(prefix)) return true
  }

  if (lower.startsWith('.')) return true

  if (/^\{[0-9a-f-]+\}$/i.test(lower)) return true

  if (/^kb\d{4,}(-\d+)*$/i.test(lower)) return true

  return false
}
