using DiNho.Capture.Poc.Logging;
using System.Runtime.InteropServices;
using Microsoft.Win32;
using Windows.Win32;

namespace DiNho.Capture.Poc;

internal static class Program
{
    private static bool _forceSoftware;
    private static bool _benchJson;
    private static int _durationSeconds;

    private static async Task Main(string[] args)
    {
        _forceSoftware = args.Contains("--force-software");
        _benchJson = args.Contains("--bench-json");
        var durationIdx = Array.IndexOf(args, "--duration");
        if (durationIdx >= 0 && durationIdx + 1 < args.Length)
            _durationSeconds = int.Parse(args[durationIdx + 1]);

        if (args.Length > 0 && args[0] == "--test")
        {
            await ProgramBenchmark.RunTestsAsync();
            return;
        }

        if (args.Length > 0 && args[0] == "--encoders")
        {
            ProgramBenchmark.TestEncoders();
            return;
        }

        if (args.Length > 0 && args[0] == "--probe-nvenc")
        {
            ProgramBenchmark.ProbeNvencPresets(
                args.Length > 1 ? args[1] : "1920",
                args.Length > 2 ? args[2] : "1080",
                args.Length > 3 ? args[3] : "60");
            return;
        }

        if (args.Length > 0 && (args[0] == "--bench" || args[0] == "--bench-json"))
        {
            await ProgramBenchmark.RunBenchmarkAsync(_benchJson);
            return;
        }

        if (args.Length > 0 && args[0] == "--validate")
        {
            await ProgramBenchmark.ValidateCaptureAsync();
            return;
        }

        if (args.Length > 0 && args[0] is "--help" or "-h" or "/?")
        {
            ProgramBenchmark.ShowHelp();
            return;
        }

        await RunEngine();
    }

    private static async Task RunEngine()
    {
        Console.WriteLine("=== DiNho Clips Engine v1.0.0 ===");
        Console.WriteLine();

        SetupGlobalExceptionHandler();
        SetAppUserModelId();
        CheckGpuDriver();

        if (_forceSoftware)
            Console.WriteLine("  Modo: force-software (encoder CPU)");
        Console.WriteLine();

        using var engine = new EngineCoordinator(forceSoftware: _forceSoftware);
        await engine.StartAsync();

        var tcs = new TaskCompletionSource();
        Console.CancelKeyPress += (s, e) =>
        {
            e.Cancel = true;
            tcs.TrySetResult();
        };

        if (_durationSeconds > 0)
        {
            Console.WriteLine($"Gravando por {_durationSeconds}s. Pressione Ctrl+C para parar antes.");
            using var timer = new Timer(_ => tcs.TrySetResult(), null, _durationSeconds * 1000, Timeout.Infinite);
            await tcs.Task;
        }
        else
        {
            Console.WriteLine("Pressione Ctrl+C para parar.");
            await tcs.Task;
        }

        await engine.StopAsync();
        Console.WriteLine("Engine parado.");
    }

    internal static string? CheckGpuDriver()
    {
        try
        {
            using var key = Registry.LocalMachine.OpenSubKey(
                @"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000");
            if (key != null)
            {
                var name = key.GetValue("DriverDesc")?.ToString() ?? "?";
                var version = key.GetValue("DriverVersion")?.ToString() ?? "?";
                var date = key.GetValue("DriverDate")?.ToString() ?? "?";
                Console.WriteLine($"  GPU: {name} (driver v{version}, {date})");
                return $"{name} v{version}";
            }
            else
            {
                Console.WriteLine("  GPU: não detectada");
                return null;
            }
        }
        catch
        {
            Console.WriteLine("  GPU: não foi possível detectar");
            return null;
        }
    }

    /// <summary>
    /// Define o AppUserModelId para o processo.
    /// Necessário para Windows.Graphics.Capture (WGC) funcionar em processos
    /// não-APPX (modo installed/packaged).
    /// Sem este ID, WGC pode falhar com ArgumentException "Parâmetro incorreto"
    /// porque o WinRT não consegue ativar o GraphicsCaptureItem corretamente.
    /// </summary>
    private static void SetAppUserModelId()
    {
        try
        {
            const string appId = "DiNho.ClipsEngine";
            var hr = PInvoke.SetCurrentProcessExplicitAppUserModelID(appId);
            if (hr == 0)
                Console.WriteLine($"[Program] AppUserModelId set to '{appId}'");
            else
                Console.Error.WriteLine($"[Program] SetCurrentProcessExplicitAppUserModelID falhou: HRESULT=0x{hr:X8}");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[Program] SetAppUserModelId exceção: {ex.Message}");
        }
    }

    // SetCurrentProcessExplicitAppUserModelID — generated by CsWin32 (NativeMethods.txt)

    private static void SetupGlobalExceptionHandler()
    {
        AppDomain.CurrentDomain.UnhandledException += (sender, args) =>
        {
            var ex = args.ExceptionObject as Exception;
            var crashLog = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "DiNhoClips", "crash", $"crash_{DateTime.Now:yyyyMMdd_HHmmss}.txt");

            var dir = Path.GetDirectoryName(crashLog);
            if (dir != null) Directory.CreateDirectory(dir);

            File.WriteAllText(crashLog,
                $"DiNho Clips Crash Report\n" +
                $"Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}\n" +
                $"OS: {Environment.OSVersion}\n" +
                $"Runtime: {RuntimeInformation.FrameworkDescription}\n" +
                $"Exception: {ex?.GetType().FullName}\n" +
                $"Message: {ex?.Message}\n" +
                $"Stack: {ex?.StackTrace}\n");

            Console.Error.WriteLine($"[FATAL] Crash inesperado. Log salvo em: {crashLog}");
        };
    }
}
